CREATE USER zabbix WITH password 'ZBX5_FBSD12_PSQL12_TSDB17';
CREATE TABLESPACE zabbix OWNER zabbix LOCATION '/data/pgsql';
CREATE DATABASE zabbix WITH OWNER = zabbix TABLESPACE = zabbix ENCODING ='UTF8';